apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gptai-cz-tls
spec:
  secretName: gptai-cz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gptai.cz
  dnsNames:
    - gptai.cz
    - www.gptai.cz


